version: "3"
services:
  course-work-cinema-service:
    build: .
    env_file:
      - config/
    ports:
      - 8080:8080
    volumes:
      - ./certs/kafka:/certs/kafka
      - ./certs/postgres:/certs/postgres
    depends_on:
      - kafka
      - postgres
    command:
      - ./wait-for-it.sh
      - kafka:9092
      - --
      - ./wait-for-it.sh
      - postgres:5432
      - --
      - payment-order-projection-service

  kafka:
    image: bitnami/kafka:3.6.2
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - 9094:9094

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - 10100:8080
    depends_on:
      - kafka

  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.5
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_DISABLE_POSTFIX: "true"
    ports:
      - 10200:80
    depends_on:
      - postgres
